Added a spell named nox
gabru-md/LinuxSpells pull request #15
Opened 2018-06-02 03:13 UTC by Ananthavijay

Nox is a spell that shutdowns your computer. If this works add it 😄 

Thanks,
Anantha Vijay

2018-06-02 06:10 UTC, gabru-md requested changes

2018-06-02 06:10 UTC, gabru-md commented on spells/nox.txt
> +Typing"nox" in your terminal will make the computer shutdown.
give a space between `Typing` and `nox`

2018-06-02 12:33 UTC, Ananthavijay commented
check it now @gabru-md

2018-06-05 03:03 UTC, gabru-md approved these changes

2018-06-05 03:04 UTC, merged